version: '3.9'

services:
  money_splitter:
    container_name: money_splitter
    image: golang
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
      - cache_db
  go_db:
    container_name: go_db
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/money_splitter.sql
  cache_db:
    container_name: cache_db
    image: redis:alpine
    env_file:
      - ./.env
    ports:
      - '6379:6379'
volumes:  
  pgdata: {}
