CREATE DATABASE money_splitter;
\c money_splitter;

CREATE TABLE IF NOT EXISTS "USER" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "GROUP" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  GROUP_NAME VARCHAR(255) NOT NULL UNIQUE,
  SIMPLIFY_TXN BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "USER_IN_GROUPS" (
  user_id VARCHAR(255) NOT NULL,
  group_id VARCHAR(255) NOT NULL,

  FOREIGN KEY (user_id) REFERENCES "USER"(ID),
  FOREIGN KEY (group_id) REFERENCES "GROUP"(ID)
);

CREATE TABLE IF NOT EXISTS "TXN" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  AMOUNT DECIMAL(10,2) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  DATE DATE NOT NULL,
  GROUP_ID VARCHAR(255) NOT NULL,
  PAYER_ID VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (group_id) REFERENCES "GROUP"(ID),
  FOREIGN KEY (payer_id) REFERENCES "USER"(ID)
);

CREATE TABLE IF NOT EXISTS "GROUP_TXNS" (
  user_id VARCHAR(255) NOT NULL,
  group_id VARCHAR(255) NOT NULL,
  TXN_ID VARCHAR(255) NOT NULL,

  FOREIGN KEY (user_id) REFERENCES "USER"(ID),
  FOREIGN KEY (group_id) REFERENCES "GROUP"(ID),
  FOREIGN KEY (txn_id) REFERENCES "TXN"(ID)
);
