CREATE DATABASE money_splitter;
\c money_splitter;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "USER" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  IS_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "GROUP" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  GROUP_NAME VARCHAR(255) NOT NULL UNIQUE,
  GROUP_ADMIN VARCHAR(255) NOT NULL,
  SIMPLIFY_TXN BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (GROUP_ADMIN) REFERENCES "USER"(ID),
);

CREATE TABLE IF NOT EXISTS "USER_IN_GROUPS" (
  USER_ID VARCHAR(255) NOT NULL,
  GROUP_ID VARCHAR(255) NOT NULL,

  FOREIGN KEY (USER_ID) REFERENCES "USER"(ID),
  FOREIGN KEY (GROUP_ID) REFERENCES "GROUP"(ID)
);

CREATE TABLE IF NOT EXISTS "TXN" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  AMOUNT DECIMAL(10,2) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  DATE DATE NOT NULL,
  GROUP_ID VARCHAR(255) NOT NULL,
  PAYER_ID VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (GROUP_ID) REFERENCES "GROUP"(ID),
  FOREIGN KEY (PAYER_ID) REFERENCES "USER"(ID)
);

CREATE TABLE IF NOT EXISTS "GROUP_TXNS" (
  user_id VARCHAR(255) NOT NULL,
  group_id VARCHAR(255) NOT NULL,
  TXN_ID VARCHAR(255) NOT NULL,

  FOREIGN KEY (USER_ID) REFERENCES "USER"(ID),
  FOREIGN KEY (GROUP_ID) REFERENCES "GROUP"(ID),
  FOREIGN KEY (TXN_ID) REFERENCES "TXN"(ID)
);
